### ISSUE TITLE
homebrew formula uses old sha1

### ISSUE THREAD

**Issue by tomquas** [postmodern/gem_home#13]
$ brew install --HEAD https://raw.github.com/postmodern/gem_home/master/homebrew/gem_home.rb
######################################################################## 100.0%
Warning: Calling Formula.sha1 is deprecated!
Use Formula.sha256 instead.
/Users/tom/Library/Caches/Homebrew/Formula/gem_home.rb:6:in `<class:GemHome>'

Warning: Calling SoftwareSpec#sha1 is deprecated!
Use SoftwareSpec#sha256 instead.
/Users/tom/Library/Caches/Homebrew/Formula/gem_home.rb:6:in `<class:GemHome>'

Warning: Calling Resource#sha1 is deprecated!
Use Resource#sha256 instead.
/Users/tom/Library/Caches/Homebrew/Formula/gem_home.rb:6:in `<class:GemHome>'

**Comment by tomquas** [comment]
thanks 👍
